# -*- coding: utf-8 -*-
"""day7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l-hWsT4iTuQzltxIHU1nKNwY6CLRHeol
"""

import pandas as pd
import plotly.express as px
import streamlit as st
mydata = pd.read_csv('buycomputer.csv')

# Printing the dataswet shape
print ("Dataset Length: ", len(mydata))
print ("Dataset Shape: ", mydata.shape)
mydata

"""#Total values counts of Class Number"""
st.subheader('Total values counts of Class Number')
val = mydata['class'].value_counts()
st.dataframe(val)

"""#Visualize class size of each age category"""

res1=mydata.groupby(['age', 'class'])[['class']].size().fillna(0).reset_index(name='class_size')
st.write(res1)
agegp = px.bar(data_frame=res1, x='age', y='class_size', color='class', title='Class Size of Age').update_layout(xaxis_title='age', yaxis_title='class size')
st.plotly_chart(agegp)

"""#Visualize class size of each income category"""

res2=mydata.groupby(['income', 'class'])[['class']].size().fillna(0).reset_index(name='class_size')
incomeres = px.bar(data_frame=res2, x='income', y='class_size', color='class', title='Class Size of Income').update_layout(xaxis_title='income', yaxis_title='class size')
st.plotly_chart(incomeres)
"""#Visualize class size of each studen category"""

res3=mydata.groupby(['studen', 'class'])[['class']].size().fillna(0).reset_index(name='class_size')
stures = px.bar(data_frame=res3, x='studen', y='class_size', color='class', title='Class Size of Student').update_layout(xaxis_title='student', yaxis_title='class size')
st.plotly_chart(stures)

"""#Visualize class size of each creadit rating category"""

res4=mydata.groupby(['credit rating', 'class'])[['class']].size().fillna(0).reset_index(name='class_size')
crres = px.bar(data_frame=res4, x='credit rating', y='class_size', color='class', title='Class Size of Student').update_layout(xaxis_title='credit rating', yaxis_title='class size')
st.plotly_chart(crres)


#Create a heatmap to visualize correlation
corr_matrix = mydata.apply(lambda x : pd.factorize(x)[0]).corr(method='pearson', min_periods=1)#to convert categorical values in each column of mydata into numerical labels using factorize()
st.write(corr_matrix)


hmap=px.imshow(corr_matrix, text_auto=True)
st.plotly_chart(hmap)
